# -*- coding: utf-8 -*-
"""Copy of DUDL_FFN_FFNonMNIST.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E0_Yk-htDjRWxzuK47_MmEP-EhmVzFFq

# COURSE: A deep understanding of deep learning
## SECTION: FFNs
### LECTURE: FFN to classify digits
#### TEACHER: Mike X Cohen, sincxpress.com
##### COURSE URL: udemy.com/course/deeplearning_x/?couponCode=202401
"""

# import libraries
import numpy as np

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader,TensorDataset
from sklearn.model_selection import train_test_split

import matplotlib.pyplot as plt
import matplotlib_inline.backend_inline
matplotlib_inline.backend_inline.set_matplotlib_formats('svg')

"""# Import and process the data"""

# import dataset (comes with colab!)
data = np.loadtxt(open('sample_data/mnist_train_small.csv','rb'),delimiter=',')
#Remove 7s!

Sevns = data[data[:,0] == 7.0]
data = data[data[:,0] != 7.0]
# # extract labels (number IDs) and remove from data
labels = data[:,0]
data   = data[:,1:]

LabelsSevns = Sevns[:,0]
Sevns = Sevns[:,1:]

# normalize the data to a range of [0 1]
dataNorm = data / np.max(data)
SevnsNorm = Sevns / np.max(Sevns)

fig,ax = plt.subplots(1,2,figsize=(10,4))
ax[0].hist(data.flatten(),50)
ax[0].set_xlabel('Pixel intensity values')
ax[0].set_ylabel('Count')
ax[0].set_title('Histogram of original data')

ax[1].hist(dataNorm.flatten(),50)
ax[1].set_xlabel('Pixel intensity values')
ax[1].set_ylabel('Count')
ax[1].set_title('Histogram of normalized data')

plt.show()

"""# Create train/test groups using DataLoader"""

# Step 1: convert to tensor
dataT   = torch.tensor( dataNorm ).float()
labelsT = torch.tensor( labels ).long() # long = int64

SevnsT   = torch.tensor( SevnsNorm ).float()
SevnslabelsT = torch.tensor( LabelsSevns ).long() # long = int64

# # Step 2: use scikitlearn to split the data
# Sevns_train_data,Sevns_test_data, Sevns_train_labels, Sevns_test_labels = train_test_split(dataT, labelsT, test_size=.1)
# train_data,test_data, train_labels,test_labels = train_test_split(dataT, labelsT, test_size=.1)


# Step 3: convert into PyTorch Datasets
train_data = TensorDataset(dataT,labelsT)
test_data  = TensorDataset(SevnsT,SevnslabelsT)

# Step 4: translate into dataloader objects
batchsize    = 32
train_loader = DataLoader(train_data,batch_size=batchsize,shuffle=True,drop_last=True)
test_loader  = DataLoader(test_data,batch_size=test_data.tensors[0].shape[0])

# Commented out IPython magic to ensure Python compatibility.
# check all variables in workspace
# %whos

"""# Create the DL model"""

# create a class for the model
def createTheMNISTNet():

  class mnistNet(nn.Module):
    def __init__(self):
      super().__init__()

      ### input layer
      self.input = nn.Linear(784,64)

      ### hidden layer
      self.fc1 = nn.Linear(64,32)
      self.fc2 = nn.Linear(32,32)

      ### output layer
      self.output = nn.Linear(32,10)

    # forward pass
    def forward(self,x):
      x = F.relu( self.input(x) )
      x = F.relu( self.fc1(x) )
      x = F.relu( self.fc2(x) )
      return  self.output(x)

  # create the model instance
  net = mnistNet()

  # loss function
  lossfun = nn.CrossEntropyLoss()

  # optimizer
  optimizer = torch.optim.SGD(net.parameters(),lr=.01)

  return net,lossfun,optimizer

"""# Create a function that trains the model"""

# a function that trains the model

def function2trainTheModel():

  # number of epochs
  numepochs = 40

  # create a new model
  net,lossfun,optimizer = createTheMNISTNet()

  # initialize losses
  losses    = torch.zeros(numepochs)
  trainAcc  = []
  testAcc   = []
  yHat = torch.zeros(len(LabelsSevns))

  # loop over epochs
  for epochi in range(numepochs):

    # loop over training data batches
    batchAcc  = []
    batchLoss = []
    for X,y in train_loader:

      # forward pass and loss
      yHat = net(X)
      loss = lossfun(yHat,y)

      # backprop
      optimizer.zero_grad()
      loss.backward()
      optimizer.step()

      # loss from this batch
      batchLoss.append(loss.item())

      # compute accuracy
      matches = torch.argmax(yHat,axis=1) == y     # booleans (false/true)
      matchesNumeric = matches.float()             # convert to numbers (0/1)
      accuracyPct = 100*torch.mean(matchesNumeric) # average and x100
      batchAcc.append( accuracyPct )               # add to list of accuracies
    # end of batch loop...

    # now that we've trained through the batches, get their average training accuracy
    trainAcc.append( np.mean(batchAcc) )

    # and get average losses across the batches
    losses[epochi] = np.mean(batchLoss)

    # test accuracy
    X,y = next(iter(test_loader)) # extract X,y from test dataloader
    yHat = net(X)

    # compare the following really long line of code to the training accuracy lines
    testAcc.append( 100*torch.mean((torch.argmax(yHat,axis=1)==y).float()) )

  # end epochs

  # function output
  return trainAcc,testAcc,losses,net, yHat

"""# Run the model and show the results!"""

trainAcc,testAcc,losses,net, yHat = function2trainTheModel()

predictednum = torch.argmax(yHat,axis=1)

fig,ax = plt.subplots(1,3,figsize=(16,5))

ax[0].plot(trainAcc,label='Train')
ax[0].set_xlabel('Epochs')
ax[0].set_ylabel('Accuracy (%)')
ax[0].set_title('Train accuracy without sevens')
ax[0].legend()

ax[1].plot(testAcc,label='Test')
ax[1].set_xlabel('Epochs')
ax[1].set_ylabel('Accuracy (%)')
ax[1].set_title('Tests accucary with only sevens')
ax[1].legend()

ax[2].hist(predictednum)
ax[2].set_xlabel('PRedicted number')
ax[2].set_ylabel('Frequency')
ax[2].set_title('Frequency of predicted numbers ')
ax[2].legend()


plt.show()

predictednum

"""# Inspect the results in more detail"""

# run the model through for the test data
# X,y = next(iter(test_loader))
# predictions = net(X).detach()

# predictions

# # Evidence for all numbers from one sample
# sample2show = 120

# plt.bar(range(10),predictions[sample2show]) # try adding exp!
# plt.xticks(range(10))
# plt.xlabel('Number')
# plt.ylabel('Evidence for that number')
# plt.title('True number was %s' %y[sample2show].item())
# plt.show()

# # find the errors
# errors = np.where( torch.max(predictions,axis=1)[1] != y )[0]
# print(errors)

# # Evidence for all numbers from one sample
# sample2show = 10

# fig,ax = plt.subplots(1,2,figsize=(14,5))

# ax[0].bar(range(10),np.exp(predictions[errors[sample2show]]))
# ax[0].set_xticks(range(10))
# ax[0].set_xlabel('Number')
# ax[0].set_ylabel('Evidence for that number')
# ax[0].set_title('True number: %s, model guessed %s'
#                 %( y[errors[sample2show]].item(), torch.argmax(predictions[errors[sample2show]]).item() ))

# ax[1].imshow( np.reshape(X[errors[sample2show],:],(28,28)) ,cmap='gray')

# plt.show()

"""# Additional explorations"""

# 1) Average together the correct 7's and the error 7's, and make images of them (that is, one image
#    of all correct 7's and one image of all incorrectly labeled 7's). How do they look?
#
# 2) Repeat #1 for all numbers to produce a 2x10 matrix of images with corrects on top
#    and errors on the bottom.
#
# 3) Identify "almost errors," which we can define as correct categorizations that had a probability of
#    e.g., >.1 for any other number. Make images of some of these numbers. Can you understand why the model
#    was confused?
#
# 4) I didn't use .train(), .eval(), or no_grad() here. Is that a problem? Can you add those in without checking
#    other notebooks?
#